ALTER TABLE "Complaint"
ADD COLUMN "category" TEXT NOT NULL DEFAULT 'General',
ADD COLUMN "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
ADD COLUMN "department" TEXT NOT NULL DEFAULT 'Civic Response Cell',
ADD COLUMN "sentiment" TEXT NOT NULL DEFAULT 'concerned',
ADD COLUMN "confidence" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN "suggestedAction" TEXT NOT NULL DEFAULT '',
ADD COLUMN "socialPost" TEXT NOT NULL DEFAULT '',
ADD COLUMN "image" TEXT NOT NULL DEFAULT '',
ADD COLUMN "latitude" DOUBLE PRECISION NOT NULL DEFAULT 25.5941,
ADD COLUMN "longitude" DOUBLE PRECISION NOT NULL DEFAULT 85.1376,
ADD COLUMN "upvotes" INTEGER NOT NULL DEFAULT 0;
